site_name: Math Resource Studio Help
site_url: https://rdinch.github.io/MathResourceStudio-Help/
site_description: Complete help documentation for Math Resource Studio 8

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting Started:
    - "What's New": getting-started/what's-new.md
    - "Creating math documents": getting-started/creating-math-documents.md
    - "Create a new document": getting-started/create-a-new-document.md
  - Activities:
    - Basic Operations:
      - "Basic Addition": activities/basic-addition.md
      - "Basic Subtraction": activities/basic-subtraction.md
      - "Basic Multiplication": activities/basic-multiplication.md
      - "Basic Division": activities/basic-division.md
    - Fractions:
      - "Fractions": activities/fractions.md
      - "Equivalent Fractions": activities/equivalent-fractions.md
      - "Fractions Addition": activities/fractions-addition.md
  - Reference:
    - "Program Reference": reference/reference.md
  - Worksheets:
    - "Creating": worksheets/creating.md
    - "Properties": worksheets/properties.md
    - "Answer Sheets": worksheets/answer-sheets.md
