site_name: Math Resource Studio Help
site_url: https://rdinch.github.io/MathResourceStudio-Help/
site_description: Complete help documentation for Math Resource Studio 8

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting Started:
    - "Change Page Setup   Margins, Orientation, Paper Size": getting-started/change-page-setup---margins,-orientation,-paper-size.md
    - "Close A Document": getting-started/close-a-document.md
    - "Create A New Document": getting-started/create-a-new-document.md
    - "Creating Math Documents": getting-started/creating-math-documents.md
    - "Print A Document": getting-started/print-a-document.md
    - "Save, Open And Edit A Template": getting-started/save,-open-and-edit-a-template.md
    - "Save And Open A Document": getting-started/save-and-open-a-document.md
    - "Save Your Options Settings": getting-started/save-your-options-settings.md
    - "What's New": getting-started/what's-new.md
  - Activities:
    - ADVANCED NUMBER OPERATIONS:
      - "Advanced Addition": activities/Advanced Number Operations/advanced-addition.md
      - "Advanced Division": activities/Advanced Number Operations/advanced-division.md
      - "Advanced Division: No Remainders": activities/Advanced Number Operations/advanced-division---no-remainders.md
      - "Advanced Division: Remainders": activities/Advanced Number Operations/advanced-division---remainders.md
      - "Advanced Division Selected Divisors": activities/Advanced Number Operations/advanced-division-selected-divisors.md
      - "Advanced Multiplication": activities/Advanced Number Operations/advanced-multiplication.md
      - "Advanced Multiplication: Selected Multipliers": activities/Advanced Number Operations/advanced-multiplication---selected-multipliers.md
      - "Advanced Subtraction": activities/Advanced Number Operations/advanced-subtraction.md
      - "Mixed Advanced Operations": activities/Advanced Number Operations/mixed-advanced-operations.md
      - "Multiple Addends": activities/Advanced Number Operations/multiple-addends.md
      - "Multiple Operations": activities/Advanced Number Operations/multiple-operations.md
      - "Multiple Operations Missing Operations": activities/Advanced Number Operations/multiple-operations-missing-operations.md
      - "Powers Of Ten": activities/Advanced Number Operations/powers-of-ten.md
    - ALGEBRA:
      - "Equations: Defined Variable": activities/Algebra/equations---defined-variable.md
      - "Equations: Single Variable (One Side)": activities/Algebra/equations---single-variable-(one-side).md
      - "Inequalities": activities/Algebra/inequalities.md
      - "Number Problems": activities/Algebra/number-problems.md
      - "Pre Algebra Equations One Side": activities/Algebra/pre-algebra-equations-one-side.md
      - "Pre Algebra Equations Two Sides": activities/Algebra/pre-algebra-equations-two-sides.md
      - "Simplifying Expressions": activities/Algebra/simplifying-expressions.md
    - BASIC NUMBER OPERATIONS:
      - "Basic Addition": activities/Basic Number Operations/basic-addition.md
      - "Basic Addition And Regrouping": activities/Basic Number Operations/basic-addition-and-regrouping.md
      - "Basic Addition: Doubles": activities/Basic Number Operations/basic-addition---doubles.md
      - "Basic Addition Fixed Addend": activities/Basic Number Operations/basic-addition-fixed-addend.md
      - "Basic Division": activities/Basic Number Operations/basic-division.md
      - "Basic Multiplication": activities/Basic Number Operations/basic-multiplication.md
      - "Basic Multiplication Fixed Factor": activities/Basic Number Operations/basic-multiplication-fixed-factor.md
      - "Basic Subtraction": activities/Basic Number Operations/basic-subtraction.md
      - "Basic Subtraction And Regrouping": activities/Basic Number Operations/basic-subtraction-and-regrouping.md
      - "Fact Families": activities/Basic Number Operations/fact-families.md
      - "Input Output": activities/Basic Number Operations/input-output.md
      - "Make Sum": activities/Basic Number Operations/make-sum.md
      - "Match Ups": activities/Basic Number Operations/match-ups.md
      - "Mixed Basic Operations": activities/Basic Number Operations/mixed-basic-operations.md
      - "Multiple Operations Addition Subtraction": activities/Basic Number Operations/multiple-operations-addition-subtraction.md
      - "Pictorial Addition": activities/Basic Number Operations/pictorial-addition.md
      - "Quick Facts": activities/Basic Number Operations/quick-facts.md
      - "Word Problems: Addition": activities/Basic Number Operations/word-problems---addition.md
      - "Word Problems: Division": activities/Basic Number Operations/word-problems---division.md
      - "Word Problems: Multiplication": activities/Basic Number Operations/word-problems---multiplication.md
      - "Word Problems: Subtraction": activities/Basic Number Operations/word-problems---subtraction.md
    - CONSUMER MATH:
      - "Compound Interest": activities/Consumer Math/compound-interest.md
      - "Counting Money": activities/Consumer Math/counting-money.md
      - "Money In Words": activities/Consumer Math/money-in-words.md
      - "Shopping Problems": activities/Consumer Math/shopping-problems.md
      - "Shopping Problems Ii": activities/Consumer Math/shopping-problems-ii.md
      - "Simple Interest": activities/Consumer Math/simple-interest.md
      - "Wages": activities/Consumer Math/wages.md
    - COORDINATES:
      - "Cartesian Coordinates: Four Quadrants": activities/Coordinates/cartesian-coordinates---four-quadrants.md
      - "Cartesian Coordinates: Single Quadrant": activities/Coordinates/cartesian-coordinates---single-quadrant.md
      - "Plot Lines": activities/Coordinates/plot-lines.md
    - CUSTOM:
      - "Custom Questions": activities/Custom/custom-questions.md
      - "Custom Word Problems": activities/Custom/custom-word-problems.md
    - FRACTIONS:
      - "Comparing Fractions": activities/Fractions/comparing-fractions.md
      - "Division With Whole Numbers": activities/Fractions/division-with-whole-numbers.md
      - "Equivalent Fractions": activities/Fractions/equivalent-fractions.md
      - "Fraction Identification: Grids": activities/Fractions/fraction-identification---grids.md
      - "Fraction Identification: Rectangles": activities/Fractions/fraction-identification---rectangles.md
      - "Fractions Addition": activities/Fractions/fractions-addition.md
      - "Fractions And Decimals": activities/Fractions/fractions-and-decimals.md
      - "Fractions Division": activities/Fractions/fractions-division.md
      - "Fractions Multiple Operations": activities/Fractions/fractions-multiple-operations.md
      - "Fractions Multiplication": activities/Fractions/fractions-multiplication.md
      - "Fractions Subtraction": activities/Fractions/fractions-subtraction.md
      - "Mixed Numbers And Improper Fractions": activities/Fractions/mixed-numbers-and-improper-fractions.md
      - "Mixed Operations With Fractions": activities/Fractions/mixed-operations-with-fractions.md
      - "Multiplication With Whole Numbers": activities/Fractions/multiplication-with-whole-numbers.md
      - "Order Fractional Values": activities/Fractions/order-fractional-values.md
      - "Simplifying Fractions": activities/Fractions/simplifying-fractions.md
      - "Word Problems Fractions Addition": activities/Fractions/word-problems-fractions-addition.md
      - "Word Problems Fractions Division": activities/Fractions/word-problems-fractions-division.md
      - "Word Problems Fractions Multiplication": activities/Fractions/word-problems-fractions-multiplication.md
      - "Word Problems Fractions Subtraction": activities/Fractions/word-problems-fractions-subtraction.md
    - GEOMETRY:
      - "Angles": activities/Geometry/angles.md
      - "Area Shapes": activities/Geometry/area-shapes.md
      - "Circles": activities/Geometry/circles.md
      - "Measuring Lines": activities/Geometry/measuring-lines.md
      - "Measuring Rectangles": activities/Geometry/measuring-rectangles.md
      - "Perimeter And Area": activities/Geometry/perimeter-and-area.md
      - "Polygons": activities/Geometry/polygons.md
      - "Pythagorean Theorem": activities/Geometry/pythagorean-theorem.md
      - "Volume": activities/Geometry/volume.md
      - "Volume Cubes": activities/Geometry/volume-cubes.md
    - GRAPH PAPER:
      - "Bar Graphs": activities/Graph Paper/bar-graphs.md
      - "Line Graphs": activities/Graph Paper/line-graphs.md
      - "Xy Graphs": activities/Graph Paper/xy-graphs.md
    - GRAPHING:
      - "Make A Bar Graph": activities/Graphing/make-a-bar-graph.md
      - "Make A Line Graph": activities/Graphing/make-a-line-graph.md
    - MEASUREMENT:
      - "Metric Conversion": activities/Measurement/metric-conversion.md
      - "Metric Weights And Measures": activities/Measurement/metric-weights-and-measures.md
      - "Reading Thermometers": activities/Measurement/reading-thermometers.md
      - "Temperature Conversion": activities/Measurement/temperature-conversion.md
      - "Us Weights And Measures": activities/Measurement/us-weights-and-measures.md
    - NUMBER CONCEPTS:
      - "Exponents": activities/Number Concepts/exponents.md
      - "Mean Median Mode Range": activities/Number Concepts/mean-median-mode-range.md
      - "Roman Arabic Comparison": activities/Number Concepts/roman-arabic-comparison.md
      - "Roman Numerals": activities/Number Concepts/roman-numerals.md
      - "Roots": activities/Number Concepts/roots.md
      - "Scientific Notation": activities/Number Concepts/scientific-notation.md
    - NUMBER LINES:
      - "Number Lines: Decimals": activities/Number Lines/number-lines---decimals.md
      - "Number Lines: Fractions": activities/Number Lines/number-lines---fractions.md
      - "Number Lines: Integers": activities/Number Lines/number-lines---integers.md
    - NUMERATION:
      - "Associative Property": activities/Numeration/associative-property.md
      - "Before After Between": activities/Numeration/before-after-between.md
      - "Circle The Numbers": activities/Numeration/circle-the-numbers.md
      - "Commutative Property": activities/Numeration/commutative-property.md
      - "Comparing Numbers": activities/Numeration/comparing-numbers.md
      - "Count How Many": activities/Numeration/count-how-many.md
      - "Counting Patterns": activities/Numeration/counting-patterns.md
      - "Count Up And Down": activities/Numeration/count-up-and-down.md
      - "Distributive Property": activities/Numeration/distributive-property.md
      - "Expanded Notation": activities/Numeration/expanded-notation.md
      - "Factors": activities/Numeration/factors.md
      - "Greatest Common Factor": activities/Numeration/greatest-common-factor.md
      - "Lowest Common Multiple": activities/Numeration/lowest-common-multiple.md
      - "Multiples": activities/Numeration/multiples.md
      - "Ordering Numbers": activities/Numeration/ordering-numbers.md
      - "Place Value": activities/Numeration/place-value.md
      - "Prime Numbers": activities/Numeration/prime-numbers.md
      - "Rounding Numbers": activities/Numeration/rounding-numbers.md
    - PROBABILITY:
      - "Probability Spinner": activities/Probability/probability-spinner.md
    - PUZZLES:
      - "Across Downs": activities/Puzzles/across-downs.md
      - "Addition Box": activities/Puzzles/addition-box.md
      - "Diamond Math": activities/Puzzles/diamond-math.md
      - "Magic Squares": activities/Puzzles/magic-squares.md
      - "Magic Stars": activities/Puzzles/magic-stars.md
      - "Multiplication Box": activities/Puzzles/multiplication-box.md
      - "Number Patterns": activities/Puzzles/number-patterns.md
      - "Secret Trails": activities/Puzzles/secret-trails.md
      - "Sudoku": activities/Puzzles/sudoku.md
    - RATIO AND PERCENT:
      - "Percent And Decimals": activities/Ratio and Percent/percent-and-decimals.md
      - "Percent Of Numbers: Advanced": activities/Ratio and Percent/percent-of-numbers---advanced.md
      - "Percent Of Numbers: Basic": activities/Ratio and Percent/percent-of-numbers---basic.md
      - "Ratio Conversions": activities/Ratio and Percent/ratio-conversions.md
      - "Word Problems Percent": activities/Ratio and Percent/word-problems-percent.md
    - TABLES AND DRILLS:
      - "Circle Drill Addition": activities/Tables and Drills/circle-drill-addition.md
      - "Circle Drill Division": activities/Tables and Drills/circle-drill-division.md
      - "Circle Drill Multiplication": activities/Tables and Drills/circle-drill-multiplication.md
      - "Circle Drill Subtraction": activities/Tables and Drills/circle-drill-subtraction.md
      - "Counting Table": activities/Tables and Drills/counting-table.md
      - "Table Drill Addition": activities/Tables and Drills/table-drill-addition.md
      - "Table Drill Division": activities/Tables and Drills/table-drill-division.md
      - "Table Drill Multiplication": activities/Tables and Drills/table-drill-multiplication.md
      - "Table Drill Subtraction": activities/Tables and Drills/table-drill-subtraction.md
    - TIME:
      - "Telling Time": activities/Time/telling-time.md
      - "Time Conversions": activities/Time/time-conversions.md
      - "Time Passages": activities/Time/time-passages.md
  - Reference:
    - "Add A Background Picture": reference/add-a-background-picture.md
    - "Add A Fraction Line": reference/add-a-fraction-line.md
    - "Add A Line": reference/add-a-line.md
    - "Add An Epigraph": reference/add-an-epigraph.md
    - "Add A Number Line": reference/add-a-number-line.md
    - "Add A Picture": reference/add-a-picture.md
    - "Add A Title": reference/add-a-title.md
    - "Add A Title Group": reference/add-a-title-group.md
    - "Add Text": reference/add-text.md
    - "Add Vertical Spacing": reference/add-vertical-spacing.md
    - "Advanced Number Operations": reference/advanced-number-operations.md
    - "Answers   Show Key, Answer Banks, Key Color And Answer Lines": reference/answers---show-key,-answer-banks,-key-color-and-answer-lines.md
    - "Basic Number Operations": reference/basic-number-operations.md
    - "Basic Number Operations Word Problem Templates": reference/basic-number-operations-word-problem-templates.md
    - "Change The Document Numbering": reference/change-the-document-numbering.md
    - "Change The Program Options": reference/change-the-program-options.md
    - "Check Your Spelling": reference/check-your-spelling.md
    - "Consumer Math": reference/consumer-math.md
    - "Coordinates": reference/coordinates.md
    - "Currency Collection": reference/currency-collection.md
    - "Custom": reference/custom.md
    - "Custom Questions Editor": reference/custom-questions-editor.md
    - "Custom Word Problem Templates": reference/custom-word-problem-templates.md
    - "Delete, Cut, Copy, Paste Or Move Sections And Elements": reference/delete,-cut,-copy,-paste-or-move-sections-and-elements.md
    - "Edit Equation Patterns": reference/edit-equation-patterns.md
    - "Edit Problem Templates With Solve For Option": reference/edit-problem-templates-with-solve-for-option.md
    - "Edit Shopping Items": reference/edit-shopping-items.md
    - "Edit Word Problem Names": reference/edit-word-problem-names.md
    - "Edit Word Problem Objects": reference/edit-word-problem-objects.md
    - "Epigraphs Editor": reference/epigraphs-editor.md
    - "Exercise Sets": reference/exercise-sets.md
    - "Global Colors   Set The Font Colors": reference/global-colors---set-the-font-colors.md
    - "Global Fonts   Set The Font": reference/global-fonts---set-the-font.md
    - "Graphing": reference/graphing.md
    - "Graph Lines In Slope Intercept Form": reference/graph-lines-in-slope-intercept-form.md
    - "Graph Paper": reference/graph-paper.md
    - "Image Collection": reference/image-collection.md
    - "Just The Answers   Answer Block": reference/just-the-answers---answer-block.md
    - "Navigation Bar Plus Serial Number": reference/navigation-bar-plus-serial-number.md
    - "Number Concepts": reference/number-concepts.md
    - "Numeration": reference/numeration.md
    - "Picture Editor": reference/picture-editor.md
    - "Place Value Names Editor": reference/place-value-names-editor.md
    - "Probability": reference/probability.md
    - "Puzzles": reference/puzzles.md
    - "Reference": reference/reference.md
    - "Set Defaults For Font, Numbering And Answer Lines": reference/set-defaults-for-font,-numbering-and-answer-lines.md
    - "Tables And Drills": reference/tables-and-drills.md
    - "Thesaurus": reference/thesaurus.md
  - Tutorials:
    - "Add A Design Element": tutorials/add-a-design-element.md
    - "Add A Design Group": tutorials/add-a-design-group.md
    - "Add A Footer": tutorials/add-a-footer.md
    - "Add A Header": tutorials/add-a-header.md
    - "Add An Exercise Set": tutorials/add-an-exercise-set.md
    - "Add A Section To The Document": tutorials/add-a-section-to-the-document.md
    - "Add A Section With One Column": tutorials/add-a-section-with-one-column.md
    - "Add A Section With Two Auto Flow Columns": tutorials/add-a-section-with-two-auto-flow-columns.md
    - "Add A Section With Two Manual Columns": tutorials/add-a-section-with-two-manual-columns.md
    - "Create A Design Group": tutorials/create-a-design-group.md
    - "Customize The Questions   Generate Or Manual Edit": tutorials/customize-the-questions---generate-or-manual-edit.md
    - "Delete A Design Group": tutorials/delete-a-design-group.md
    - "Design Elements": tutorials/design-elements.md
    - "Show Hide   Global Settings": tutorials/show-hide---global-settings.md
    - "Working With The Answer Sheet": tutorials/working-with-the-answer-sheet.md
  - Options:
    - "Answer Bank Display Options": options/answer-bank-display-options.md
    - "Exercise Set Display Options": options/exercise-set-display-options.md
    - "Instructions Display Options": options/instructions-display-options.md
    - "Numbering Display Options": options/numbering-display-options.md
    - "Title Display Options": options/title-display-options.md
