site_name: Math Resource Studio
site_url: https://rdinch.github.io/MathResourceStudio-Help/
site_description: Complete help documentation for Math Resource Studio 8

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css?v=2

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: date

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - What's New: what's-new.md
  - Creating Math Documents:
    - "Add A Design Element": creating-math-documents/add-a-design-element.md
    - "Add A Footer": creating-math-documents/add-a-footer.md
    - "Add A Header": creating-math-documents/add-a-header.md
    - "Add An Exercise Set": creating-math-documents/add-an-exercise-set.md
    - "Answer Sheets": creating-math-documents/answer-sheets.md
    - "Answers   Show Key, Answer Banks, Key Color And Answer Lines": creating-math-documents/answers---show-key,-answer-banks,-key-color-and-answer-lines.md
    - "Change Page Setup   Margins, Orientation, Paper Size": creating-math-documents/change-page-setup---margins,-orientation,-paper-size.md
    - "Change The Document Numbering": creating-math-documents/change-the-document-numbering.md
    - "Check Your Spelling": creating-math-documents/check-your-spelling.md
    - "Close A Document": creating-math-documents/close-a-document.md
    - "Create A New Document": creating-math-documents/create-a-new-document.md
    - "Customize The Questions   Generate Or Manual Edit": creating-math-documents/customize-the-questions---generate-or-manual-edit.md
    - "Just The Answers   Answer Block": creating-math-documents/just-the-answers---answer-block.md
    - "Navigation Bar Plus Serial Number": creating-math-documents/navigation-bar-plus-serial-number.md
    - "Print A Document": creating-math-documents/print-a-document.md
    - "Save, Open And Edit A Template": creating-math-documents/save,-open-and-edit-a-template.md
    - "Save And Open A Document": creating-math-documents/save-and-open-a-document.md
    - "Save Your Options Settings": creating-math-documents/save-your-options-settings.md
    - "Set Defaults For Font, Numbering And Answer Lines": creating-math-documents/set-defaults-for-font,-numbering-and-answer-lines.md
    - "Show Hide   Global Settings": creating-math-documents/show-hide---global-settings.md
    - "Working With The Answer Sheet": creating-math-documents/working-with-the-answer-sheet.md
    - Design Groups:
      - "Add A Design Group": creating-math-documents/design-groups/add-a-design-group.md
      - "Create A Design Group": creating-math-documents/design-groups/create-a-design-group.md
      - "Delete A Design Group": creating-math-documents/design-groups/delete-a-design-group.md
    - Document Sections:
      - "Add A Section To The Document": creating-math-documents/document_sections/add-a-section-to-the-document.md
      - "Add A Section With One Column": creating-math-documents/document_sections/add-a-section-with-one-column.md
      - "Add A Section With Two Auto Flow Columns": creating-math-documents/document_sections/add-a-section-with-two-auto-flow-columns.md
      - "Add A Section With Two Manual Columns": creating-math-documents/document_sections/add-a-section-with-two-manual-columns.md
  - Exercise Sets:
    - ADVANCED NUMBER OPERATIONS:
      - "Advanced Addition": exercise-sets/Advanced Number Operations/advanced-addition.md
      - "Advanced Division": exercise-sets/Advanced Number Operations/advanced-division.md
      - "Advanced Division: No Remainders": exercise-sets/Advanced Number Operations/advanced-division---no-remainders.md
      - "Advanced Division: Remainders": exercise-sets/Advanced Number Operations/advanced-division---remainders.md
      - "Advanced Division Selected Divisors": exercise-sets/Advanced Number Operations/advanced-division-selected-divisors.md
      - "Advanced Multiplication": exercise-sets/Advanced Number Operations/advanced-multiplication.md
      - "Advanced Multiplication: Selected Multipliers": exercise-sets/Advanced Number Operations/advanced-multiplication---selected-multipliers.md
      - "Advanced Subtraction": exercise-sets/Advanced Number Operations/advanced-subtraction.md
      - "Mixed Advanced Operations": exercise-sets/Advanced Number Operations/mixed-advanced-operations.md
      - "Multiple Addends": exercise-sets/Advanced Number Operations/multiple-addends.md
      - "Multiple Operations": exercise-sets/Advanced Number Operations/multiple-operations.md
      - "Multiple Operations Missing Operations": exercise-sets/Advanced Number Operations/multiple-operations-missing-operations.md
      - "Powers Of Ten": exercise-sets/Advanced Number Operations/powers-of-ten.md
    - ALGEBRA:
      - "Equations: Defined Variable": exercise-sets/Algebra/equations---defined-variable.md
      - "Equations: Single Variable (One Side)": exercise-sets/Algebra/equations---single-variable-(one-side).md
      - "Inequalities": exercise-sets/Algebra/inequalities.md
      - "Number Problems": exercise-sets/Algebra/number-problems.md
      - "Pre Algebra Equations One Side": exercise-sets/Algebra/pre-algebra-equations-one-side.md
      - "Pre Algebra Equations Two Sides": exercise-sets/Algebra/pre-algebra-equations-two-sides.md
      - "Simplifying Expressions": exercise-sets/Algebra/simplifying-expressions.md
    - BASIC NUMBER OPERATIONS:
      - "Basic Addition": exercise-sets/Basic Number Operations/basic-addition.md
      - "Basic Addition And Regrouping": exercise-sets/Basic Number Operations/basic-addition-and-regrouping.md
      - "Basic Addition: Doubles": exercise-sets/Basic Number Operations/basic-addition---doubles.md
      - "Basic Addition Fixed Addend": exercise-sets/Basic Number Operations/basic-addition-fixed-addend.md
      - "Basic Division": exercise-sets/Basic Number Operations/basic-division.md
      - "Basic Multiplication": exercise-sets/Basic Number Operations/basic-multiplication.md
      - "Basic Multiplication Fixed Factor": exercise-sets/Basic Number Operations/basic-multiplication-fixed-factor.md
      - "Basic Subtraction": exercise-sets/Basic Number Operations/basic-subtraction.md
      - "Basic Subtraction And Regrouping": exercise-sets/Basic Number Operations/basic-subtraction-and-regrouping.md
      - "Fact Families": exercise-sets/Basic Number Operations/fact-families.md
      - "Input Output": exercise-sets/Basic Number Operations/input-output.md
      - "Make Sum": exercise-sets/Basic Number Operations/make-sum.md
      - "Match Ups": exercise-sets/Basic Number Operations/match-ups.md
      - "Mixed Basic Operations": exercise-sets/Basic Number Operations/mixed-basic-operations.md
      - "Multiple Operations Addition Subtraction": exercise-sets/Basic Number Operations/multiple-operations-addition-subtraction.md
      - "Pictorial Addition": exercise-sets/Basic Number Operations/pictorial-addition.md
      - "Quick Facts": exercise-sets/Basic Number Operations/quick-facts.md
      - "Word Problems: Addition": exercise-sets/Basic Number Operations/word-problems---addition.md
      - "Word Problems: Division": exercise-sets/Basic Number Operations/word-problems---division.md
      - "Word Problems: Multiplication": exercise-sets/Basic Number Operations/word-problems---multiplication.md
      - "Word Problems: Subtraction": exercise-sets/Basic Number Operations/word-problems---subtraction.md
    - CONSUMER MATH:
      - "Compound Interest": exercise-sets/Consumer Math/compound-interest.md
      - "Counting Money": exercise-sets/Consumer Math/counting-money.md
      - "Money In Words": exercise-sets/Consumer Math/money-in-words.md
      - "Shopping Problems": exercise-sets/Consumer Math/shopping-problems.md
      - "Shopping Problems Ii": exercise-sets/Consumer Math/shopping-problems-ii.md
      - "Simple Interest": exercise-sets/Consumer Math/simple-interest.md
      - "Wages": exercise-sets/Consumer Math/wages.md
    - COORDINATES:
      - "Cartesian Coordinates: Four Quadrants": exercise-sets/Coordinates/cartesian-coordinates---four-quadrants.md
      - "Cartesian Coordinates: Single Quadrant": exercise-sets/Coordinates/cartesian-coordinates---single-quadrant.md
      - "Plot Lines": exercise-sets/Coordinates/plot-lines.md
    - CUSTOM:
      - "Custom Questions": exercise-sets/Custom/custom-questions.md
      - "Custom Word Problems": exercise-sets/Custom/custom-word-problems.md
    - FRACTIONS:
      - "Comparing Fractions": exercise-sets/Fractions/comparing-fractions.md
      - "Division With Whole Numbers": exercise-sets/Fractions/division-with-whole-numbers.md
      - "Equivalent Fractions": exercise-sets/Fractions/equivalent-fractions.md
      - "Fraction Identification: Grids": exercise-sets/Fractions/fraction-identification---grids.md
      - "Fraction Identification: Rectangles": exercise-sets/Fractions/fraction-identification---rectangles.md
      - "Fractions Addition": exercise-sets/Fractions/fractions-addition.md
      - "Fractions And Decimals": exercise-sets/Fractions/fractions-and-decimals.md
      - "Fractions Division": exercise-sets/Fractions/fractions-division.md
      - "Fractions Multiple Operations": exercise-sets/Fractions/fractions-multiple-operations.md
      - "Fractions Multiplication": exercise-sets/Fractions/fractions-multiplication.md
      - "Fractions Subtraction": exercise-sets/Fractions/fractions-subtraction.md
      - "Mixed Numbers And Improper Fractions": exercise-sets/Fractions/mixed-numbers-and-improper-fractions.md
      - "Mixed Operations With Fractions": exercise-sets/Fractions/mixed-operations-with-fractions.md
      - "Multiplication With Whole Numbers": exercise-sets/Fractions/multiplication-with-whole-numbers.md
      - "Order Fractional Values": exercise-sets/Fractions/order-fractional-values.md
      - "Simplifying Fractions": exercise-sets/Fractions/simplifying-fractions.md
      - "Word Problems Fractions Addition": exercise-sets/Fractions/word-problems-fractions-addition.md
      - "Word Problems Fractions Division": exercise-sets/Fractions/word-problems-fractions-division.md
      - "Word Problems Fractions Multiplication": exercise-sets/Fractions/word-problems-fractions-multiplication.md
      - "Word Problems Fractions Subtraction": exercise-sets/Fractions/word-problems-fractions-subtraction.md
    - GEOMETRY:
      - "Angles": exercise-sets/Geometry/angles.md
      - "Area Shapes": exercise-sets/Geometry/area-shapes.md
      - "Circles": exercise-sets/Geometry/circles.md
      - "Measuring Lines": exercise-sets/Geometry/measuring-lines.md
      - "Measuring Rectangles": exercise-sets/Geometry/measuring-rectangles.md
      - "Perimeter And Area": exercise-sets/Geometry/perimeter-and-area.md
      - "Polygons": exercise-sets/Geometry/polygons.md
      - "Pythagorean Theorem": exercise-sets/Geometry/pythagorean-theorem.md
      - "Volume": exercise-sets/Geometry/volume.md
      - "Volume Cubes": exercise-sets/Geometry/volume-cubes.md
    - GRAPH PAPER:
      - "Bar Graphs": exercise-sets/Graph Paper/bar-graphs.md
      - "Line Graphs": exercise-sets/Graph Paper/line-graphs.md
      - "Xy Graphs": exercise-sets/Graph Paper/xy-graphs.md
    - GRAPHING:
      - "Make A Bar Graph": exercise-sets/Graphing/make-a-bar-graph.md
      - "Make A Line Graph": exercise-sets/Graphing/make-a-line-graph.md
    - MEASUREMENT:
      - "Metric Conversion": exercise-sets/Measurement/metric-conversion.md
      - "Metric Weights And Measures": exercise-sets/Measurement/metric-weights-and-measures.md
      - "Reading Thermometers": exercise-sets/Measurement/reading-thermometers.md
      - "Temperature Conversion": exercise-sets/Measurement/temperature-conversion.md
      - "Us Weights And Measures": exercise-sets/Measurement/us-weights-and-measures.md
    - NUMBER CONCEPTS:
      - "Exponents": exercise-sets/Number Concepts/exponents.md
      - "Mean Median Mode Range": exercise-sets/Number Concepts/mean-median-mode-range.md
      - "Roman Arabic Comparison": exercise-sets/Number Concepts/roman-arabic-comparison.md
      - "Roman Numerals": exercise-sets/Number Concepts/roman-numerals.md
      - "Roots": exercise-sets/Number Concepts/roots.md
      - "Scientific Notation": exercise-sets/Number Concepts/scientific-notation.md
    - NUMBER LINES:
      - "Number Lines: Decimals": exercise-sets/Number Lines/number-lines---decimals.md
      - "Number Lines: Fractions": exercise-sets/Number Lines/number-lines---fractions.md
      - "Number Lines: Integers": exercise-sets/Number Lines/number-lines---integers.md
    - NUMERATION:
      - "Associative Property": exercise-sets/Numeration/associative-property.md
      - "Before After Between": exercise-sets/Numeration/before-after-between.md
      - "Circle The Numbers": exercise-sets/Numeration/circle-the-numbers.md
      - "Commutative Property": exercise-sets/Numeration/commutative-property.md
      - "Comparing Numbers": exercise-sets/Numeration/comparing-numbers.md
      - "Count How Many": exercise-sets/Numeration/count-how-many.md
      - "Counting Patterns": exercise-sets/Numeration/counting-patterns.md
      - "Count Up And Down": exercise-sets/Numeration/count-up-and-down.md
      - "Distributive Property": exercise-sets/Numeration/distributive-property.md
      - "Expanded Notation": exercise-sets/Numeration/expanded-notation.md
      - "Factors": exercise-sets/Numeration/factors.md
      - "Greatest Common Factor": exercise-sets/Numeration/greatest-common-factor.md
      - "Lowest Common Multiple": exercise-sets/Numeration/lowest-common-multiple.md
      - "Multiples": exercise-sets/Numeration/multiples.md
      - "Ordering Numbers": exercise-sets/Numeration/ordering-numbers.md
      - "Place Value": exercise-sets/Numeration/place-value.md
      - "Prime Numbers": exercise-sets/Numeration/prime-numbers.md
      - "Rounding Numbers": exercise-sets/Numeration/rounding-numbers.md
    - PROBABILITY:
      - "Probability Spinner": exercise-sets/Probability/probability-spinner.md
    - PUZZLES:
      - "Across Downs": exercise-sets/Puzzles/across-downs.md
      - "Addition Box": exercise-sets/Puzzles/addition-box.md
      - "Diamond Math": exercise-sets/Puzzles/diamond-math.md
      - "Magic Squares": exercise-sets/Puzzles/magic-squares.md
      - "Magic Stars": exercise-sets/Puzzles/magic-stars.md
      - "Multiplication Box": exercise-sets/Puzzles/multiplication-box.md
      - "Number Patterns": exercise-sets/Puzzles/number-patterns.md
      - "Secret Trails": exercise-sets/Puzzles/secret-trails.md
      - "Sudoku": exercise-sets/Puzzles/sudoku.md
    - RATIO AND PERCENT:
      - "Percent And Decimals": exercise-sets/Ratio and Percent/percent-and-decimals.md
      - "Percent Of Numbers: Advanced": exercise-sets/Ratio and Percent/percent-of-numbers---advanced.md
      - "Percent Of Numbers: Basic": exercise-sets/Ratio and Percent/percent-of-numbers---basic.md
      - "Ratio Conversions": exercise-sets/Ratio and Percent/ratio-conversions.md
      - "Word Problems Percent": exercise-sets/Ratio and Percent/word-problems-percent.md
    - TABLES AND DRILLS:
      - "Circle Drill Addition": exercise-sets/Tables and Drills/circle-drill-addition.md
      - "Circle Drill Division": exercise-sets/Tables and Drills/circle-drill-division.md
      - "Circle Drill Multiplication": exercise-sets/Tables and Drills/circle-drill-multiplication.md
      - "Circle Drill Subtraction": exercise-sets/Tables and Drills/circle-drill-subtraction.md
      - "Counting Table": exercise-sets/Tables and Drills/counting-table.md
      - "Table Drill Addition": exercise-sets/Tables and Drills/table-drill-addition.md
      - "Table Drill Division": exercise-sets/Tables and Drills/table-drill-division.md
      - "Table Drill Multiplication": exercise-sets/Tables and Drills/table-drill-multiplication.md
      - "Table Drill Subtraction": exercise-sets/Tables and Drills/table-drill-subtraction.md
    - TIME:
      - "Telling Time": exercise-sets/Time/telling-time.md
      - "Time Conversions": exercise-sets/Time/time-conversions.md
      - "Time Passages": exercise-sets/Time/time-passages.md
  - Design Elements:
    - "Add a Background Picture": design-elements/add-a-background-picture.md
    - "Add a Fraction Line": design-elements/add-a-fraction-line.md
    - "Add a Line": design-elements/add-a-line.md
    - "Add a Number Line": design-elements/add-a-number-line.md
    - "Add a Picture": design-elements/add-a-picture.md
    - "Add a Title": design-elements/add-a-title.md
    - "Add a Title Group": design-elements/add-a-title-group.md
    - "Add n Epigraph": design-elements/add-an-epigraph.md
    - "Add Text": design-elements/add-text.md
    - "Add Vertical Spacing": design-elements/add-vertical-spacing.md
  - Reference:
    - "Basic Number Operations Word Problem Templates": reference/basic-number-operations-word-problem-templates.md
    - "Change The Program Options": reference/change-the-program-options.md
    - "Currency Collection": reference/currency-collection.md
    - "Custom Questions Editor": reference/custom-questions-editor.md
    - "Custom Word Problem Templates": reference/custom-word-problem-templates.md
    - "Delete, Cut, Copy, Paste Or Move Sections And Elements": reference/delete,-cut,-copy,-paste-or-move-sections-and-elements.md
    - "Edit Equation Patterns": reference/edit-equation-patterns.md
    - "Edit Problem Templates With Solve For Option": reference/edit-problem-templates-with-solve-for-option.md
    - "Edit Shopping Items": reference/edit-shopping-items.md
    - "Edit Word Problem Names": reference/edit-word-problem-names.md
    - "Edit Word Problem Objects": reference/edit-word-problem-objects.md
    - "Epigraphs Editor": reference/epigraphs-editor.md
    - "Global Colors   Set The Font Colors": reference/global-colors---set-the-font-colors.md
    - "Global Fonts   Set The Font": reference/global-fonts---set-the-font.md
    - "Graph Lines In Slope Intercept Form": reference/graph-lines-in-slope-intercept-form.md
    - "Image Collection": reference/image-collection.md
    - "Picture Editor": reference/picture-editor.md
    - "Place Value Names Editor": reference/place-value-names-editor.md
    - "Thesaurus": reference/thesaurus.md
  - Options:
    - "Answer Bank Display Options": options/answer-bank-display-options.md
    - "Exercise Set Display Options": options/exercise-set-display-options.md
    - "Instructions Display Options": options/instructions-display-options.md
    - "Numbering Display Options": options/numbering-display-options.md
    - "Title Display Options": options/title-display-options.md
